version: '3'

services:
  solr:
    image: solr:alpine
    volumes:
      - ./solr/collection1:/var/solr/data/collection1
      - ./solr/logadmin:/var/solr/data/logadmin
    # Expose the solr port iff you need to collect the logs of remote machines
    ports:
      - 10000:8983

  log-collector:
    image: dbjtech/docker-log-collector
    depends_on:
      - solr
    environment:
      - TZ=Asia/Shanghai
      - VERBOSE=true
      - SOLR_HOST=solr
      - SOLR_PORT=8983
      - LOG_HOST_NAME=localhost
    volumes:
      # Run the following cmd in powershell if you are using windows docker
      # $Env:COMPOSE_CONVERT_WINDOWS_PATHS=1
      - /var/run/docker.sock:/var/run/docker.sock

  search:
    build: ./
    depends_on:
      - solr
    environment:
      - PORT=80
      - SOLR_HOST=solr
      - SOLR_PORT=8983
      - VERBOSE=true
    ports:
      - 3000:80
